import { Course, Creator, CourseModule, CourseReview, Testimonial } from '@/types';

export const MOCK_CREATOR: Creator = {
  id: 'purepearl-studio',
  name: 'PurePearl Studio',
  handle: 'purepearlstudio',
  title: 'Passionate UI/UX, Web designer',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  bio: 'Welcome to the creative world of [Creator\'s Name]. Here, you\'ll discover the passion, expertise, and inspiration that drive my creative journey. Let\'s explore and learn together!',
  description: 'ive into my creative portfolio, showcasing a glimpse of my artistic endeavors. From digital designs to multimedia projects, each piece tells a unique story. Explore the world of creativity with me.',
  productsCount: 3,
  followersCount: 12,
  isFollowing: false,
};

export const MOCK_STUDENT_AVATARS = [
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&auto=format&fit=crop&q=80',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&auto=format&fit=crop&q=80',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=80&auto=format&fit=crop&q=80',
  'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=80&auto=format&fit=crop&q=80',
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'c1',
    slug: 'learn-figma-from-basic',
    title: 'Learn Figma from Basic',
    creator: {
      id: 'purepearl-studio',
      name: 'purepearl studio',
      avatar: MOCK_CREATOR.avatar,
    },
    image: '/skill/skil1.jpg',
    lessonsCount: 17,
    duration: '2 hours 16 mins',
    commentsCount: 59,
    rating: 4.5,
    level: 'Beginner',
    price: 25,
    priceType: 'lifetime',
    category: 'Design',
    featured: true,
  },
  {
    id: 'c2',
    slug: 'build-digital-asset',
    title: 'Build Digital Asset',
    subtitle: 'Unlock the Power of Digital Creation with Expert Guidance',
    creator: {
      id: 'purepearl-studio',
      name: 'purepearl studio',
      avatar: MOCK_CREATOR.avatar,
    },
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    lessonsCount: 17,
    duration: '2 hours 16 mins',
    commentsCount: 59,
    rating: 4.5,
    level: 'Beginner',
    price: 25,
    priceType: 'lifetime',
    category: 'Featured',
    featured: true,
  },
  {
    id: 'c3',
    slug: 'the-power-of-big-data',
    title: 'the Power of Big Data',
    creator: {
      id: 'purepearl-studio',
      name: 'purepearl studio',
      avatar: MOCK_CREATOR.avatar,
    },
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    lessonsCount: 17,
    duration: '2 hours 16 mins',
    commentsCount: 59,
    rating: 4.5,
    level: 'Beginner',
    price: 25,
    priceType: 'lifetime',
    category: 'IT & Software',
    featured: true,
  },
  {
    id: 'c4',
    slug: 'balancing-productivity-and-life',
    title: 'Balancing Productivity an...',
    creator: {
      id: 'purepearl-studio',
      name: 'purepearl studio',
      avatar: MOCK_CREATOR.avatar,
    },
    image: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=80',
    lessonsCount: 17,
    duration: '2 hours 16 mins',
    commentsCount: 59,
    rating: 4.5,
    level: 'Beginner',
    price: 25,
    priceType: 'lifetime',
    category: 'Productivity',
    featured: false,
  },
  {
    id: 'c5',
    slug: 'mastering-money-management',
    title: 'Mastering Money Manage...',
    creator: {
      id: 'purepearl-studio',
      name: 'purepearl studio',
      avatar: MOCK_CREATOR.avatar,
    },
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop&q=80',
    lessonsCount: 17,
    duration: '2 hours 16 mins',
    commentsCount: 59,
    rating: 4.5,
    level: 'Beginner',
    price: 25,
    priceType: 'lifetime',
    category: 'Finance',
    featured: false,
  },
  {
    id: 'c6',
    slug: 'from-idea-to-startup-success',
    title: 'From Idea to Startup Succ...',
    creator: {
      id: 'purepearl-studio',
      name: 'purepearl studio',
      avatar: MOCK_CREATOR.avatar,
    },
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    lessonsCount: 17,
    duration: '2 hours 16 mins',
    commentsCount: 59,
    rating: 4.5,
    level: 'Beginner',
    price: 25,
    priceType: 'lifetime',
    category: 'Business',
    featured: false,
  },
];

export const MOCK_MODULES: CourseModule[] = [
  {
    id: 'm1',
    moduleNumber: 1,
    title: 'Module 1: Introduction to Digital Assets',
    description: "Lay the groundwork with lessons like 'Understanding Digital Elements' and 'Navigating Design Software Tools.' Dive into the essentials of digital asset creation.",
    duration: '12 mins',
  },
  {
    id: 'm2',
    moduleNumber: 2,
    title: 'Module 2: Design Principles for Impact',
    description: "Master the principles that drive impactful designs with lessons such as 'Color Theory in Digital Design' and 'Typography Essentials.' Elevate your visual communication skills.",
    duration: '21 mins',
  },
  {
    id: 'm3',
    moduleNumber: 4,
    title: 'Module 4: User-Centric Design Strategies',
    description: "Understand 'Design Thinking in Digital Creation' and delve into 'User Experience (UX) Essentials.' Craft digital assets with a focus on user-centric design.",
    duration: '16 mins',
  },
  {
    id: 'm4',
    moduleNumber: 5,
    title: 'Module 5: Interactive Media and Engagement',
    description: "Engage your audience with lessons like 'Creating Interactive Presentations' and 'Integrating Multimedia Elements.' Master the art of creating immersive digital experiences.",
    duration: '18 mins',
  },
  {
    id: 'm5',
    moduleNumber: 6,
    title: 'Module 6: Project Showcase and Critique',
    description: "Perfect your presentation skills with 'Effective Presentation Techniques' and embrace collaboration with 'Peer Critique and Collaboration.' Showcase your work with confidence.",
    duration: '24 mins',
  },
  {
    id: 'm6',
    moduleNumber: 7,
    title: 'Module 7: Optimizing Digital Assets for Various Platforms',
    description: "Adapt your digital creations for 'Mobile Platforms' and optimize for 'Social Media.' Ensure widespread accessibility and engagement across diverse digital landscapes.",
    duration: '15 mins',
  },
];

export const MOCK_REVIEWS: CourseReview[] = [
  {
    id: 'r1',
    author: 'PurePearl Studio',
    role: 'UI/UX Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    timeAgo: 'a year ago',
    rating: 5,
    content: '"The course provided me with a comprehensive understanding of digital asset creation. The lessons were in-depth, practical, and immediately applicable to my work. Highly recommended!"',
  },
  {
    id: 'r2',
    author: 'Albert Flores',
    role: 'UI/UX Designer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    timeAgo: 'a year ago',
    rating: 5,
    content: 'This course transformed my approach to digital design. The combination of theory, hands-on exercises, and real-world applications made it a truly enriching experience. Excited to implement what I\'ve learned!',
  },
  {
    id: 'r3',
    author: 'Cody Fisher',
    role: 'UI/UX Designer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    timeAgo: 'a year ago',
    rating: 5,
    content: 'The project showcase and critique module created a collaborative environment where I could showcase my work, receive valuable feedback, and refine my skills. It added a unique and valuable dimension to the learning process.',
  },
  {
    id: 'r4',
    author: 'Brooklyn Simmons',
    role: 'UI/UX Designer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    timeAgo: 'a year ago',
    rating: 5,
    content: 'The lessons on optimizing digital assets for various platforms were particularly insightful. The course adapts to the evolving digital landscape, and the engaging content kept me motivated throughout.',
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Sarah M.',
    role: 'Enthusiastic Learner',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    content: '"ByteSpace has transformed my approach to learning. The diverse range of courses and the quality of content provided by creators have exceeded my expectations. The platform truly fosters a sense of community and lifelong learning."',
  },
  {
    id: 't2',
    name: 'James L.',
    role: 'Lifelong Learner',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    content: '"I\'ve tried several online learning platforms, and ByteSpace stands out for its vibrant community and the variety of courses available. The easy navigation and engaging content make it a go-to platform for continuous skill development."',
  },
  {
    id: 't3',
    name: 'Alex B.',
    role: 'Inspired Creator',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    content: '"As a creator, ByteSpace has been a game-changer for me. The Course Editor is user-friendly, and the support from the community is incredible. It\'s fulfilling to see my courses making a positive impact on learners globally."',
  },
];

export const CATEGORIES = [
  'Featured',
  'Music',
  'Drawing & Painting',
  'Marketing',
  'Animation',
  'Social Media',
  'UI/UX Design',
  'Creative Marketing',
  'Digital Illustration',
  'Film & Video',
  'Crafts',
  'Freelance & Entrepreneurship',
  'Graphic Design',
  'Photography',
  'Productivity',
  'Web Development',
  'Data Science',
  'Cooking',
  '+ More',
];

export const PATHS_CATEGORIES = [
  {
    id: 'p1',
    name: 'Design',
    icon: 'wrench',
  },
  {
    id: 'p2',
    name: 'Development',
    icon: 'code',
  },
  {
    id: 'p3',
    name: 'IT & Software',
    icon: 'laptop',
  },
  {
    id: 'p4',
    name: 'Business',
    icon: 'building',
  },
  {
    id: 'p5',
    name: 'Marketing',
    icon: 'megapone',
  },
  {
    id: 'p6',
    name: 'Photography',
    icon: 'camera',
  },
];
